# Generated by Django 5.1.4 on 2024-12-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(unique=True)),
                ('shorten_url', models.CharField(max_length=256, unique=True)),
                ('hits', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['target_url', 'shorten_url'], name='joints_join_target__361db3_idx')],
            },
        ),
    ]
