# Generated by Django 5.1.4 on 2024-12-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joints', '0002_joint_created_at_joint_ttl_joint_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joint',
            name='ttl',
        ),
        migrations.AddField(
            model_name='joint',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
