# Generated by Django 5.1.4 on 2025-03-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joints', '0005_joint_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joint',
            options={'ordering': ['-created_at']},
        ),
    ]
