# Generated by Django 5.1.4 on 2025-03-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joints', '0008_alter_joint_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joint',
            name='custom',
            field=models.BooleanField(default=True),
        ),
    ]
